version: '3'
services:
  njin:
    build: ./njin
    working_dir: /usr/src/app
    command: "lein run"
    ports: 
      - "8001:8001"

  gejmskrin:
    build: ./gejmskrin
    working_dir: /usr/src/app
    command: "python3 -m http.server 3000"
    ports: 
      - '3000:3000'
